name: cs236-dp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - tqdm
  - torchvision
  - pytorch
  - tensorboard
  - scipy
  - torchmetrics
  - pip:
    - torch-fidelity
